config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]

  resources :apples

  resources :recyclers

  root 'static#home'
  get '/about' => 'static#about'
  get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: :cat_pictures
  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'

end

app/models/apple.rb
class Apple < ActiveRecord::Base
  validates_presence_of :name, :diameter, :height

  validates :diameter, :numericality => {:greater_than => 0.0}
  validates :height, :numericality => {:greater_than => 0.0}

  def self.search(query)
    return all if query.blank?
    where('LOWER(name) LIKE LOWER(?)', "%#{query}%")
  end
end

app/models/recycler.rb
class Recycler < ActiveRecord::Base
  validates_presence_of :name, :address
  
  validates_format_of :phone, with: /\A\d{3}-\d{3}-\d{4}\z/, message: "isn't a correctly formatted phone number: e.g. 123-456-7890", allow_blank: true

  before_validation :format_website
validate :valid_website

def format_website
  self.website = "http://#{website}" unless website.blank? || website[/^https?/]
end

def valid_website
  return if website.blank?
  if /(\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z)/ix =~ website
    begin # check header response
      response = Net::HTTP.get_response URI.parse(website)
      return if response.kind_of?(Net::HTTPSuccess) || response.kind_of?(Net::HTTPRedirection)
      message = "doesn't appear to be a page on #{response.uri.host} (#{response.code}: #{response.msg})"
    rescue # Recover on DNS failures
      message = "doesn't seem to exist on the web"
    end
  end
  message ||= "isn't a valid web address"
  errors.add(:website, message)
end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
  before_action :only_allow_signed_in_users, except: [:index, :show]
  before_action :set_apple, only: [:show, :edit, :update, :destroy]

  # GET /apples
  # GET /apples.json
  def index
    @apples = Apple.search(params[:search])
  end

  # GET /apples/1
  # GET /apples/1.json
  def show
  end

  # GET /apples/new
  def new
    @apple = Apple.new
  end

  # GET /apples/1/edit
  def edit
  end

  # POST /apples
  # POST /apples.json
  def create
    @apple = Apple.new(apple_params)

    respond_to do |format|
      if @apple.save
        format.html { redirect_to @apple, notice: 'Apple was successfully grown.' }
        format.json { render :show, status: :created, location: @apple }
      else
        format.html { render :new }
        format.json { render json: @apple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apples/1
  # PATCH/PUT /apples/1.json
  def update
    respond_to do |format|
      if @apple.update(apple_params)
        format.html { redirect_to @apple, notice: 'Apple was successfully beefed up.' }
        format.json { render :show, status: :ok, location: @apple }
      else
        format.html { render :edit }
        format.json { render json: @apple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apples/1
  # DELETE /apples/1.json
  def destroy
    @apple.destroy
    respond_to do |format|
      format.html { redirect_to apples_url, notice: 'Apple was grotesquely consumed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apple
      @apple = Apple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apple_params
      params.require(:apple).permit(:name, :diameter, :height, :is_red)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def only_allow_signed_in_users
    unless user_signed_in?
      redirect_to sign_in_url, notice: 'You must sign in to access this part of the app.'
    end
  end

end

app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  
  before_action :set_recycler, only: [:show, :edit, :update, :destroy]
before_action :only_allow_signed_in_users, except: [:index, :show]

  # GET /recyclers
  # GET /recyclers.json
  def index
    @recyclers = Recycler.all
  end

  # GET /recyclers/1
  # GET /recyclers/1.json
  def show
  end

  # GET /recyclers/new
  def new
    @recycler = Recycler.new
  end

  # GET /recyclers/1/edit
  def edit
  end

  # POST /recyclers
  # POST /recyclers.json
  def create
    @recycler = Recycler.new(recycler_params)

    respond_to do |format|
      if @recycler.save
        format.html { redirect_to @recycler, notice: 'Recycler was successfully created.' }
        format.json { render :show, status: :created, location: @recycler }
      else
        format.html { render :new }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recyclers/1
  # PATCH/PUT /recyclers/1.json
  def update
    respond_to do |format|
      if @recycler.update(recycler_params)
        format.html { redirect_to @recycler, notice: 'Recycler was successfully updated.' }
        format.json { render :show, status: :ok, location: @recycler }
      else
        format.html { render :edit }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recyclers/1
  # DELETE /recyclers/1.json
  def destroy
    @recycler.destroy
    respond_to do |format|
      format.html { redirect_to recyclers_url, notice: 'Recycler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recycler
      @recycler = Recycler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recycler_params
      params.require(:recycler).permit(:name, :address, :phone, :website, :email, :accepts_white_computer_paper, :accepts_corrugated_cardboard, :accepts_color_separated_glass)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.find_by(email: params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Logged in!'
  else
    flash.alert = 'Invalid email/password combination. Please try again.'
    render :new
  end
end

  def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: 'Successfully signed out!'
end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end

  def new_account
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Account created!!'
    else
      flash.alert = 'Invalid email/password combination. Please try again.'
      render :new
    end
  end

private 
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end


end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recyclers_helper.rb
module RecyclersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def times
    Time.now.strftime("Today is %A, %H hours, and %S seconds!!")
  end
end

app/views/apples/_form.html.erb
<%= form_for(@apple) do |f| %>
  <% if @apple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apple.errors.count, "error") %> prohibited this apple from being saved:</h2>

      <ul>
      <% @apple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :diameter %> (cm)<br>
    <%= f.text_field :diameter %>
  </div>
  <div class="field">
    <%= f.label :height %> (cm)<br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :is_red %><br>
    <%= f.check_box :is_red %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apples/edit.html.erb
<h1>Editing Apple</h1>

<%= render 'form' %>

<%= link_to 'Show', @apple %> |
<%= link_to 'Back', apples_path %>

app/views/apples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apples</h1>

<%= form_tag apples_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Names", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Diameter (cm)</th>
      <th>Height (cm)</th>
      <th>Is red</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apples.each do |apple| %>
      <tr>
        <td><%= apple.name %></td>
        <td><%= apple.diameter %></td>
        <td><%= apple.height %></td>
        <td><%= apple.is_red %></td>
        <td><%= link_to 'Show', apple %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_apple_path(apple) %></td>
          <td><%= link_to 'Destroy', apple, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Apple', new_apple_path %>
<% end %>

app/views/apples/new.html.erb
<h1>New Apple</h1>

<%= render 'form' %>

<%= link_to 'Back', apples_path %>

app/views/apples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apple.name %>
</p>

<p>
  <strong>Diameter:</strong>
  <%= @apple.diameter %>
</p>

<p>
  <strong>Height:</strong>
  <%= @apple.height %>
</p>

<p>
  <strong>Is red:</strong>
  <%= @apple.is_red %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_apple_path(@apple) %> |
<% end %>

<%= link_to 'Back', apples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |type, message| %>
    <div class="<%= type %>">
      <p><%= message %></p>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <li>Signed in in as <%= current_user.email %></li>
    <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign In", sign_in_path %></li>
    <li><%= link_to "Create Account", new_user_path %></li>
  <% end %>

  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Cats', cat_pictures_path %></li>
    <li><%= link_to 'Recyclers Directory', recyclers_path %></li>
    <li><%= link_to 'Apples Directory', apples_path %></li>
  </ul>

<%= yield %>

</body>
</html>

app/views/recyclers/_form.html.erb
<%= form_for(@recycler) do |f| %>
  <% if @recycler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recycler.errors.count, "error") %> prohibited this recycler from being saved:</h2>

      <ul>
      <% @recycler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :accepts_white_computer_paper %><br>
    <%= f.check_box :accepts_white_computer_paper %>
  </div>
  <div class="field">
    <%= f.label :accepts_corrugated_cardboard %><br>
    <%= f.check_box :accepts_corrugated_cardboard %>
  </div>
  <div class="field">
    <%= f.label :accepts_color_separated_glass %><br>
    <%= f.check_box :accepts_color_separated_glass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recyclers/edit.html.erb
<h1>Editing Recycler</h1>

<%= render 'form' %>

<%= link_to 'Show', @recycler %> |
<%= link_to 'Back', recyclers_path %>

app/views/recyclers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recyclers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Email</th>
      <th>Accepts white computer paper</th>
      <th>Accepts corrugated cardboard</th>
      <th>Accepts color separated glass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recyclers.each do |recycler| %>
      <tr>
        <td><%= recycler.name %></td>
        <td><%= recycler.address %></td>
        <td><%= recycler.phone %></td>
        <td><%= recycler.website %></td>
        <td><%= recycler.email %></td>
        <td><%= recycler.accepts_white_computer_paper %></td>
        <td><%= recycler.accepts_corrugated_cardboard %></td>
        <td><%= recycler.accepts_color_separated_glass %></td>
        <td><%= link_to 'Show', recycler %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_recycler_path(recycler) %></td>
          <td><%= link_to 'Destroy', recycler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Recycler', new_recycler_path %>
<% end %>

app/views/recyclers/new.html.erb
<h1>New Recycler</h1>

<%= render 'form' %>

<%= link_to 'Back', recyclers_path %>

app/views/recyclers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recycler.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @recycler.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @recycler.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @recycler.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recycler.email %>
</p>

<p>
  <strong>Accepts white computer paper:</strong>
  <%= @recycler.accepts_white_computer_paper %>
</p>

<p>
  <strong>Accepts corrugated cardboard:</strong>
  <%= @recycler.accepts_corrugated_cardboard %>
</p>

<p>
  <strong>Accepts color separated glass:</strong>
  <%= @recycler.accepts_color_separated_glass %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_recycler_path(@recycler) %> |
<% end %>
<%= link_to 'Back', recyclers_path %>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Create New User" %>
  </div>
<% end %>